/**
 * Static HTML exports for claim summary and renewal comparison (MVP templates).
 */

import { mkdirSync, writeFileSync } from 'fs';
import { join } from 'path';
import type { MemoryManager } from '../memory/manager.js';
import type { CompanionEnvironment } from '../claw/companion-environment.js';

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

export function buildClaimSummaryHtml(userId: string, memory: MemoryManager): string {
  const claims = memory.getClaims(userId);
  const rows = claims
    .map(
      (c) =>
        `<tr><td>${escapeHtml(c.id)}</td><td>${escapeHtml(c.status)}</td><td>${escapeHtml(c.event_type ?? '')}</td><td>${escapeHtml(String(c.estimated_value_max ?? ''))}</td></tr>`
    )
    .join('\n');

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1"/>
  <title>InsurClaw — Claim summary</title>
  <style>
    body { font-family: system-ui, sans-serif; max-width: 720px; margin: 2rem auto; padding: 0 1rem; }
    h1 { font-size: 1.25rem; }
    table { width: 100%; border-collapse: collapse; margin-top: 1rem; }
    th, td { border: 1px solid #ccc; padding: 0.5rem; text-align: left; font-size: 0.9rem; }
    .muted { color: #555; font-size: 0.85rem; }
  </style>
</head>
<body>
  <h1>Claim summary</h1>
  <p class="muted">Generated by InsurClaw for policyholder review. Not legal advice.</p>
  <table>
    <thead><tr><th>ID</th><th>Status</th><th>Event</th><th>Est. max (€)</th></tr></thead>
    <tbody>${rows || '<tr><td colspan="4">No claims on file.</td></tr>'}</tbody>
  </table>
</body>
</html>`;
}

export function buildRenewalComparisonHtml(userId: string, memory: MemoryManager): string {
  const policies = memory.getPolicies(userId);
  const rows = policies
    .map(
      (p) =>
        `<tr><td>${escapeHtml(p.carrier ?? '')}</td><td>${escapeHtml(p.type ?? '')}</td><td>${escapeHtml(p.end_date ?? '')}</td><td>${escapeHtml(String(p.premium_annual ?? ''))}</td></tr>`
    )
    .join('\n');

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1"/>
  <title>InsurClaw — Renewal comparison</title>
  <style>
    body { font-family: system-ui, sans-serif; max-width: 720px; margin: 2rem auto; padding: 0 1rem; }
    h1 { font-size: 1.25rem; }
    table { width: 100%; border-collapse: collapse; margin-top: 1rem; }
    th, td { border: 1px solid #ccc; padding: 0.5rem; text-align: left; font-size: 0.9rem; }
    .muted { color: #555; font-size: 0.85rem; }
  </style>
</head>
<body>
  <h1>Renewal comparison</h1>
  <p class="muted">Generated by InsurClaw. Compare market quotes before renewal.</p>
  <table>
    <thead><tr><th>Carrier</th><th>Type</th><th>End date</th><th>Premium (€/yr)</th></tr></thead>
    <tbody>${rows || '<tr><td colspan="4">No policies on file.</td></tr>'}</tbody>
  </table>
</body>
</html>`;
}

export function writeHtmlArtifact(
  companion: CompanionEnvironment,
  sessionId: string,
  kind: 'claim_summary' | 'renewal_comparison',
  html: string
): string {
  companion.ensureSessionWorkspace(sessionId);
  const ts = Date.now();
  const dir = join(companion.sessionDir(sessionId), 'agent_outputs');
  mkdirSync(dir, { recursive: true });
  const filename = `export_${kind}_${ts}.html`;
  const path = join(dir, filename);
  writeFileSync(path, html, 'utf-8');
  return path;
}
